
sim:
  t_end: 10.0
  dt_log: 0.01
  x0: [0.3, 0.0, 0.0, 0.0]
  x_ref: 0.10
  theta_ref: 0.0
  u_sat: 100.0

disturbance:
  type: wind
  on: false
  seed: 23341
  Ts: 0.01
  power: 0.001
  smooth: 5

plant:
  M: 0.5
  m: 0.2
  l: 0.3
  g: 9.81
